version: "3.9"

services:
  backend:
    image: 386138156553.dkr.ecr.us-west-2.amazonaws.com/wally-backend:latest
    env_file: wally-registry-backend/.env
    build:
      context: .
      dockerfile: wally-registry-backend/Dockerfile
      args:
        - WALLY_BACKEND_BUILD_FEATURES=${WALLY_BACKEND_BUILD_FEATURES}
    ports:
      - "8000:8000"

  frontend:
    image: 386138156553.dkr.ecr.us-west-2.amazonaws.com/wally-frontend:latest
    env_file: wally-registry-frontend/.env
    ports:
      - "8001:8000"
    links:
      - backend
