version: "3.9"

services:
  backend:
    env_file: wally-registry-backend/.env
    build:
      context: .
      dockerfile: wally-registry-backend/Dockerfile
      args:
        - WALLY_BACKEND_BUILD_FEATURES=${WALLY_BACKEND_BUILD_FEATURES}
    ports:
      - "${WALLY_BACKEND_HOST_PORT:-8000}:8000"

  frontend:
    env_file: wally-registry-frontend/.env
    build:
      context: .
      dockerfile: wally-registry-frontend/Dockerfile
    ports:
      - "${WALLY_FRONTEND_HOST_PORT:-8001}:8000"
    links:
      - backend
